[package]
name = "kpdraw"
version = "0.1.0"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
edition = "2021"

[dependencies]
akaze = { version = "0.7.0", path = "../akaze" }
structopt = "0.3.26"
image = { version = "0.24", features = ["png", "jpeg"] }
imageproc = "0.23"
