[package]
name = "chapter2-first-program"
version = "0.1.0"
authors = ["codec-abc <viot.camille@outlook.com>"]
edition = "2021"

[dependencies]
cv = { version = "0.6.0", path = "../../cv" }
open = "2.0.2"
rand = "0.8.4"
tempfile = "3.3.0"
