on:
  push:
    branches:
      - main
  pull_request:

name: tests

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    env:
      CARGO_BACKTRACE: 1
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get -y install libxkbcommon-dev

      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install beta toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: beta
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features cv/serde-serialize